---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
  annotations:
    prometheus.io/probe: "true"
  labels:
{{ include "labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.internalPort }}
    nodePort: {{ .Values.service.externalPort }}
  selector:
{{ include "labels" . | indent 4 }}