---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Values.service.name .Release.Name | trunc 63 }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.internalPort }}
    nodePort: {{ .Values.service.externalPort }}
  selector:
{{ include "labels" . | indent 4 }}