---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "grafana-prometheus-datasource-%s" .Release.Name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Values.namespace }}
data:
  prometheus-datasource.json: |
    {
      "name": "prometheus",
      "type": "prometheus",
      "url": "http://prometheus:9090",
      "access": "proxy",
      "basicAuth": false
    }